### ISSUE TITLE
Missing newline/paragraph break in preformatted text

### ISSUE THREAD

**Issue by df7cb** [Debian/debiman#109]
The pg_buildext(1) manpage from postgresql-server-dev-all is rendered wrongly (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918129):

Original:
```
EXAMPLE
       debian/control.in:
             Source: postgresql-foobar
             Build-Depends: debhelper, postgresql-server-dev-all (>= 153~)
             XS-Testsuite: autopkgtest

             Package: postgresql-PGVERSION-foobar
             Depends: ${misc:Depends}, ${shlibs:Depends}, postgresql-PGVERSION
```

Rendered on https://manpages.debian.org/unstable/postgresql-server-dev-all/pg_buildext.1.en.html:
```
EXAMPLE
debian/control.in:
  Source: postgresql-foobar
  Build-Depends: debhelper, postgresql-server-dev-all (>= 153~)
  XS-Testsuite: autopkgtest
  Package: postgresql-PGVERSION-foobar
  Depends: ${misc:Depends}, ${shlibs:Depends}, postgresql-PGVERSION
```
Note that the paragraph break between the two sections is lost.

roff source:
```
.SH "EXAMPLE"
.IX Header "EXAMPLE"
.IP "\fBdebian/control.in:\fR" 4
.IX Item "debian/control.in:"
.Vb 2
\&  Source: postgresql\-foobar
\&  Build\-Depends: debhelper, postgresql\-server\-dev\-all (>= 153~)
\&
\&  Package: postgresql\-PGVERSION\-foobar
\&  Depends: ${misc:Depends}, ${shlibs:Depends}, postgresql\-PGVERSION
.Ve
```

I believe this is a bug in debiman and not in the package/manpage.
