### ISSUE TITLE
long pre formatted lines not readable

### ISSUE THREAD

**Issue by stbuehler** [Debian/debiman#85]
Hi,

this might be related to #84, although I don't think this is related to indented lines.

The following CSS snippet fixes the problem for me:

```css
.mandoc pre {
    white-space: pre-wrap;
}
```

For an example see the second command in first example in [`gpg-wks-client`](https://manpages.debian.org/experimental/gpg-wks-client/gpg-wks-client.1.en.html#Send_a_publication_request).
